EXPERIMENT:
  NAME: ""
  TAG: "dtad,res32x4,res8x4"
  PROJECT: "DTAD_Final"
DISTILLER:
  TYPE: "DTAD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 100
    OPTIM:
      TYPE: "SGD"
        LR: 0.05
        LR_DECAY_STAGES: [62, 75, 87]
        LR_DECAY_RATE: 0.1
        WEIGHT_DECAY: 1.5e-5
        MOMENTUM: 0.9
      TYPE: "Adam"
        LR: 0.001
        WEIGHT_DECAY: 1.5e-5
        MOMENTUM: 0.9
        LR: 0.05
        LR_DECAY_STAGES: [62, 75, 87]
        LR_DECAY_RATE: 0.1
        WEIGHT_DECAY: 1.5e-5
      

