EXPERIMENT:
  NAME: ""
  TAG: "dtad,vgg13,mv2"
  PROJECT: "DTAD_Final"
DISTILLER:
  TYPE: "DTAD"
  TEACHER: "vgg13"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 100
  LR: 0.05
  LR_DECAY_STAGES: [62, 75, 87]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
