EXPERIMENT:
  NAME: ""
  TAG: "dtkd,res56,res20"
  PROJECT: "DTKD_Final"
DISTILLER:
  TYPE: "DTKD"
  TEACHER: "resnet56"
  STUDENT: "resnet20"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 100
  LR: 0.05
  LR_DECAY_STAGES: [62, 75, 87]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DTKD:
  ALPHA: 1.0
  BETA: 0.5