EXPERIMENT:
  NAME: ""
  TAG: "dtad,res34,res18"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  TEST:
    BATCH_SIZE: 32
DISTILLER:
  TYPE: "DTAD"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 32
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"

EXPERIMENT:
  NAME: ""
  TAG: "dtad,res32x4,res8x4"
  PROJECT: "DTAD_Final"
