EXPERIMENT:
  NAME: ""
  TAG: "dtad,res32x4,shuv2"
  PROJECT: "DTAD_Final"
DISTILLER:
  TYPE: "DTAD"
  TEACHER: "resnet32x4"
  STUDENT: "ShuffleV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
